CREATE TABLE IF NOT EXISTS black_cards (
    id INTEGER NOT NULL PRIMARY KEY,
    content TEXT NOT NULL,
    empty_fields INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS white_cards (
    id INTEGER NOT NULL PRIMARY KEY,
    content TEXT NOT NULL
);